### ISSUE TITLE
Cannot find installation of real FFmpeg (which comes with ffprobe).. Retrying...

### ISSUE THREAD

**Issue by patriceguyot** [marl/audiosetdl#27]
Hello,

Thanks for this code !
I spent a lot of time on it, and it is about to work, but I've still got a error.

We I run the script to download audioset with slurm, I obtain the following error message for each video:
 _audiosetdl - INFO - ffmpeg output file ".../video/--i-y1v8Hy8_0_9000.mp4" could not be opened: Cannot find installation of real FFmpeg (which comes with ffprobe).. Retrying..._

I guess the ffmpeg which is executed to validate the file is NOT the ffmpeg that I installed in bin/ffmpeg Is there a way to set the path of the good ffmpeg in the code or to bypass this validation step if it is not crucial?

Thanks a lot,

Patrice

**Comment by justinsalamon** [comment]
@patriceguyot what version of ffmpeg do you have installed (also what system are you running on and how did you install it)?

There are actually 2 versions of ffmpeg out there... on earlier versions of Ubuntu ffmpeg [may point to a Libav binary](http://stackoverflow.com/a/9477756/2007700) which might be the source of your problem. If you are using anaconda, you can install the original ffmpeg version by calling `conda install -c conda-forge ffmpeg`. Otherwise, you can [obtain a static binary from the ffmpeg website](https://ffmpeg.org/download.html).

Let us know if this helped resolved your issue.

**Comment by patriceguyot** [comment]
@justinsalamon 

Many thanks for your answer.
I installed ffmpeg via anaconda as you suggested and it seems to work!

I still just have an error for some files:
_2018-06-21 13:34:46,517 - audiosetdl - WARNING - Output at /.../eval_segments/video/--i-y1v8Hy8_0_9000.mp4 was  expected to be duration 9.0 seconds, but got 8.633333333333333 seconds; Retrying...
2018-06-21 13:34:46,518 - audiosetdl - ERROR - Maximum number of retries (1) reached. Could not obtain inputs at https://.... Error: Output at .../--i-y1v8Hy8_0_9000.mp4 was expected to be duration 9.0 seconds, but got 8.633333333333333 seconds_


But I guess this is another issue and/or maybe not a problem.
Thanks a lot.

**Comment by justinsalamon** [comment]
Great, glad this solved the issue. I'll update the readme file to alert users to this issue. The errors you're getting are indeed a separate issue, please post them in a new issue if you still haven't resolved them.
